//
// !! DO NOT EDIT THIS FILE DIRECTLY !! 
// !! IT HAS BEEN AUTO-GENERATED !!
//
// This file is part of Kpapp for iOS.

import Foundation

fileprivate extension String {
    
    var localized: String {
        localizedWithFallback()
    }
    
    func localizedWithFormat(withArgs: CVarArg...) -> String {
        let format = localizedWithFallback()
        switch withArgs.count {
        case 1: return String.localizedStringWithFormat(format, withArgs[0])
        case 2: return String.localizedStringWithFormat(format, withArgs[0], withArgs[1])
        default: return String.localizedStringWithFormat(format, withArgs)
        }
    }
    
    private func localizedWithFallback(
        bundle: Bundle = Bundle.main,
        comment: String = ""
    ) -> String {
        let englishValue: String
        if let path = Bundle.main.path(forResource: "en", ofType: "lproj"),
           let bundle = Bundle(path: path) {
            englishValue = NSLocalizedString(self, bundle: bundle, comment: comment)
            if NSLocale.preferredLanguages.first == "en" {
                return englishValue
            }
        } else {
            englishValue = ""
        }
        return NSLocalizedString(
            self,
            tableName: nil,
            bundle: bundle,
            value: englishValue, // fall back to this, if translation not found
            comment: comment
        )
    }
}

enum LocalString {
    static let alert_handler_alert_failed_title = "alert_handler.alert.failed.title".localized
	static let app_macos_commands_new = "app_macos_commands.new".localized
	static let app_macos_commands_open_file = "app_macos_commands.open_file".localized
	static let app_macos_navigation_button_library = "app_macos_navigation.button.library".localized
	static let article_shortcut_main_button_help = "article_shortcut.main.button.help".localized
	static let article_shortcut_main_button_title = "article_shortcut.main.button.title".localized
	static let article_shortcut_random_button_help = "article_shortcut.random.button.help".localized
	static let article_shortcut_random_button_title_ios = "article_shortcut.random.button.title.ios".localized
	static let article_shortcut_random_button_title_mac = "article_shortcut.random.button.title.mac".localized
	static let attribute_detail_unknown = "attribute.detail.unknown".localized
	static let backup_settings_footer_text = "backup_settings.footer.text".localized
	static let backup_settings_header_text = "backup_settings.header.text".localized
	static let backup_settings_toggle_title = "backup_settings.toggle.title".localized
	static let bookmark_navigation_title = "bookmark.navigation.title".localized
	static let bookmark_overlay_empty_title = "bookmark.overlay.empty.title".localized
	static let bookmark_toolbar_show_sidebar_label = "bookmark.toolbar.show_sidebar.label".localized
	static let bookmark_button_show_help = "bookmark_button.show.help".localized
	static let bookmark_context_menu_remove_title = "bookmark_context_menu.remove.title".localized
	static let bookmark_context_menu_view_title = "bookmark_context_menu.view.title".localized
	static let browser_tab_toolbar_show_sidebar_label = "browser_tab.toolbar.show_sidebar.label".localized
	static let catalog_settings_auto_refresh_toggle = "catalog_settings.auto_refresh.toggle".localized
	static let catalog_settings_footer_text = "catalog_settings.footer.text".localized
	static let catalog_settings_header_text = "catalog_settings.header.text".localized
	static let catalog_settings_last_refresh_text = "catalog_settings.last_refresh.text".localized
	static let catalog_settings_refresh_now_button = "catalog_settings.refresh_now.button".localized
	static let catalog_settings_refreshing_text = "catalog_settings.refreshing.text".localized
	static let commands_button_actual_size = "commands.button.actual_size".localized
	static let comments_button_zoom_in = "comments.button.zoom_in".localized
	static let comments_button_zoom_out = "comments.button.zoom_out".localized
	static let common_button_cancel = "common.button.cancel".localized
	static let common_button_copied = "common.button.copied".localized
	static let common_button_copy = "common.button.copy".localized
	static let common_button_done = "common.button.done".localized
	static let common_button_go_back = "common.button.go_back".localized
	static let common_button_go_forward = "common.button.go_forward".localized
	static let common_button_no = "common.button.no".localized
	static let common_button_ok = "common.button.ok".localized
	static let common_button_print = "common.button.print".localized
	static let common_button_share = "common.button.share".localized
	static let common_button_share_as_pdf = "common.button.share_as_pdf".localized
	static let common_button_yes = "common.button.yes".localized
	static let common_dialog_button_add_bookmark = "common.dialog.button.add_bookmark".localized
	static let common_dialog_button_bookmark = "common.dialog.button.bookmark".localized
	static let common_dialog_button_open = "common.dialog.button.open".localized
	static let common_dialog_button_open_in_new_tab = "common.dialog.button.open_in_new_tab".localized
	static let common_dialog_button_remove_bookmark = "common.dialog.button.remove_bookmark".localized
	static let common_dialog_button_show_bookmarks = "common.dialog.button.show_bookmarks".localized
	static let common_export_file_alert_button_title = "common.export_file.alert.button.title".localized
	static func common_export_file_alert_description(withArgs args: CVarArg...) -> String { "common.export_file.alert.description".localizedWithFormat(withArgs: args) }
	static let common_export_file_alert_title = "common.export_file.alert.title".localized
	static let common_search = "common.search".localized
	static let common_tab_list_close = "common.tab.list.close".localized
	static let common_tab_manager_title = "common.tab.manager.title".localized
	static let common_tab_menu_close_all = "common.tab.menu.close_all".localized
	static let common_tab_menu_close_this = "common.tab.menu.close_this".localized
	static let common_tab_menu_library = "common.tab.menu.library".localized
	static let common_tab_menu_new_tab = "common.tab.menu.new_tab".localized
	static let common_tab_menu_settings = "common.tab.menu.settings".localized
	static let common_tab_navigation_title = "common.tab.navigation.title".localized
	static func download_service_complete_description(withArgs args: CVarArg...) -> String { "download_service.complete.description".localizedWithFormat(withArgs: args) }
	static let download_service_complete_title = "download_service.complete.title".localized
	static func download_service_error_description(withArgs args: CVarArg...) -> String { "download_service.error.description".localizedWithFormat(withArgs: args) }
	static let download_service_error_option_directory = "download_service.error.option_directory".localized
	static let download_service_error_option_invalid_response = "download_service.error.option_invalid_response".localized
	static let download_service_error_option_invalid_taskid = "download_service.error.option_invalid_taskid".localized
	static let download_service_error_option_unable_to_move_file = "download_service.error.option_unable_to_move_file".localized
	static let download_service_failed_description = "download_service.failed.description".localized
	static let download_task_cell_status_downloading = "download_task_cell.status.downloading".localized
	static let download_task_cell_status_failed = "download_task_cell.status.failed".localized
	static let download_task_cell_status_paused = "download_task_cell.status.paused".localized
	static let enum_category_other = "enum.category.other".localized
	static let enum_category_stackexchange = "enum.category.stackexchange".localized
	static let enum_category_ted = "enum.category.ted".localized
	static let enum_category_vikidia = "enum.category.vikidia".localized
	static let enum_category_wikibooks = "enum.category.wikibooks".localized
	static let enum_category_wikinews = "enum.category.wikinews".localized
	static let enum_category_wikipedia = "enum.category.wikipedia".localized
	static let enum_category_wikiquote = "enum.category.wikiquote".localized
	static let enum_category_wikisource = "enum.category.wikisource".localized
	static let enum_category_wikiversity = "enum.category.wikiversity".localized
	static let enum_category_wikivoyage = "enum.category.wikivoyage".localized
	static let enum_category_wiktionary = "enum.category.wiktionary".localized
	static let enum_external_link_loading_policy_always_ask = "enum.external_link_loading_policy.always_ask".localized
	static let enum_external_link_loading_policy_always_load = "enum.external_link_loading_policy.always_load".localized
	static let enum_external_link_loading_policy_never_load = "enum.external_link_loading_policy.never_load".localized
	static let enum_flavor_max = "enum.flavor.max".localized
	static let enum_flavor_mini = "enum.flavor.mini".localized
	static let enum_flavor_no_pic = "enum.flavor.no_pic".localized
	static let enum_library_language_sorting_model_a_z = "enum.library_language_sorting_model.a-z".localized
	static let enum_library_language_sorting_model_by_count = "enum.library_language_sorting_model.by_count".localized
	static let enum_libray_tab_item_categories = "enum.libray_tab_item.categories".localized
	static let enum_libray_tab_item_downloads = "enum.libray_tab_item.downloads".localized
	static let enum_libray_tab_item_new = "enum.libray_tab_item.new".localized
	static let enum_libray_tab_item_opened = "enum.libray_tab_item.opened".localized
	static let enum_navigation_item_bookmarks = "enum.navigation_item.bookmarks".localized
	static let enum_navigation_item_categories = "enum.navigation_item.categories".localized
	static let enum_navigation_item_downloads = "enum.navigation_item.downloads".localized
	static let enum_navigation_item_hotspot = "enum.navigation_item.hotspot".localized
	static let enum_navigation_item_new = "enum.navigation_item.new".localized
	static let enum_navigation_item_new_tab = "enum.navigation_item.new_tab".localized
	static let enum_navigation_item_opened = "enum.navigation_item.opened".localized
	static let enum_navigation_item_reading = "enum.navigation_item.reading".localized
	static let enum_navigation_item_settings = "enum.navigation_item.settings".localized
	static let enum_search_result_snippet_mode_disabled = "enum.search_result_snippet_mode.disabled".localized
	static let enum_search_result_snippet_mode_matches = "enum.search_result_snippet_mode.matches".localized
	static let external_link_handler_alert_ask_description = "external_link_handler.alert.ask.description".localized
	static let external_link_handler_alert_button_load_link = "external_link_handler.alert.button.load.link".localized
	static let external_link_handler_alert_not_loading_description = "external_link_handler.alert.not_loading.description".localized
	static let external_link_handler_alert_title = "external_link_handler.alert.title".localized
	static func file_import_alert_no_open_message(withArgs args: CVarArg...) -> String { "file_import.alert.no_open.message".localizedWithFormat(withArgs: args) }
	static let file_import_alert_no_open_title = "file_import.alert.no_open.title".localized
	static let flavor_tag_help_max = "flavor_tag.help.max".localized
	static let flavor_tag_help_mini = "flavor_tag.help.mini".localized
	static let flavor_tag_help_no_pic = "flavor_tag.help.no_pic".localized
	static let hotspot_action_start_hotspot_title = "hotspot.action.start_hotspot.title".localized
	static let hotspot_action_stop_hotspot_title = "hotspot.action.stop_hotspot.title".localized
	static let hotspot_error_port_already_used_by_another_app_description = "hotspot.error.port_already_used_by_another_app_description".localized
	static func hotspot_error_port_already_used_by_another_app_title(withArgs args: CVarArg...) -> String { "hotspot.error.port_already_used_by_another_app_title".localizedWithFormat(withArgs: args) }
	static let hotspot_server_active_warning = "hotspot.server_active_warning".localized
	static let hotspot_server_full_explanation = "hotspot.server_full_explanation".localized
	static let hotspot_server_wifi_only_explanation = "hotspot.server_wifi_only_explanation".localized
	static let hotspot_settings_port_number = "hotspot.settings.port_number".localized
	static func hotspot_settings_recommended_port_range(withArgs args: CVarArg...) -> String { "hotspot.settings.recommended_port_range".localizedWithFormat(withArgs: args) }
	static let language_selector_count_table_title = "language_selector.count.table.title".localized
	static let language_selector_hiding_header = "language_selector.hiding.header".localized
	static let language_selector_name_title = "language_selector.name.title".localized
	static let language_selector_navitation_title = "language_selector.navitation.title".localized
	static let language_selector_no_language_title = "language_selector.no_language.title".localized
	static let language_selector_showing_header = "language_selector.showing.header".localized
	static let language_selector_toolbar_sorting = "language_selector.toolbar.sorting".localized
	static let library_zim_file_context_copy_url = "library.zim_file_context.copy_url".localized
	static let library_zim_file_context_main_page_label = "library.zim_file_context.main_page.label".localized
	static let library_zim_file_context_random_label = "library.zim_file_context.random.label".localized
	static let library_zim_file_details_side_panel_message = "library.zim_file_details.side_panel.message".localized
	static let library_refresh_error_parse_description = "library_refresh_error.parse.description".localized
	static let library_refresh_error_process_description = "library_refresh_error.process.description".localized
	static let library_refresh_error_retrieve_description = "library_refresh_error.retrieve.description".localized
	static let library_refresh_time_last = "library_refresh_time.last".localized
	static let library_refresh_time_never = "library_refresh_time.never".localized
	static let library_settings_auto_refresh_toggle = "library_settings.auto_refresh.toggle".localized
	static let library_settings_button_refresh_now = "library_settings.button.refresh_now".localized
	static let library_settings_catalog_title = "library_settings.catalog.title".localized
	static let library_settings_catalog_warning_text = "library_settings.catalog_warning.text".localized
	static let library_settings_downloads_title = "library_settings.downloads.title".localized
	static let library_settings_languages_title = "library_settings.languages.title".localized
	static let library_settings_last_refresh_text = "library_settings.last_refresh.text".localized
	static let library_settings_new_download_task_description = "library_settings.new-download-task-description".localized
	static let library_settings_toggle_cellular = "library_settings.toggle.cellular".localized
	static let multi_zim_files_selected_description_count = "multi.zim_files_selected.description_count".localized
	static let multi_zim_files_selected_sidebar_title = "multi.zim_files_selected.sidebar_title".localized
	static let outline_button_outline_empty_message = "outline_button.outline.empty.message".localized
	static let outline_button_outline_help = "outline_button.outline.help".localized
	static let outline_button_outline_title = "outline_button.outline.title".localized
	static let payment_confirm_button_title = "payment.confirm.button.title".localized
	static let payment_description_label = "payment.description.label".localized
	static let payment_donate_title = "payment.donate.title".localized
	static let payment_error_description = "payment.error.description".localized
	static let payment_error_title = "payment.error.title".localized
	static let payment_monthly_support_label = "payment.monthly_support.label".localized
	static let payment_selection_average_monthly_donation_subtitle = "payment.selection.average_monthly_donation.subtitle".localized
	static let payment_selection_custom_amount = "payment.selection.custom_amount".localized
	static let payment_selection_last_year_average_subtitle = "payment.selection.last_year_average.subtitle".localized
	static let payment_selection_option_monthly = "payment.selection.option.monthly".localized
	static let payment_selection_option_one_time = "payment.selection.option.one_time".localized
	static let payment_success_description = "payment.success.description".localized
	static let payment_success_title = "payment.success.title".localized
	static let payment_summary_title = "payment.summary.title".localized
	static let payment_summary_page_title = "payment.summary_page.title".localized
	static let payment_support_button_label = "payment.support_button.label".localized
	static let payment_support_fallback_message = "payment.support_fallback_message".localized
	static let payment_textfield_custom_amount_label = "payment.textfield.custom_amount.label".localized
	static let reading_settings_external_link_title = "reading_settings.external_link.title".localized
	static let reading_settings_search_snippet_title = "reading_settings.search_snippet.title".localized
	static let reading_settings_tab_reading = "reading_settings.tab.reading".localized
	static let reading_settings_zoom_reset_button = "reading_settings.zoom.reset.button".localized
	static let reading_settings_zoom_title = "reading_settings.zoom.title".localized
	static let search_result_button_clear = "search_result.button.clear".localized
	static let search_result_filter_hearder_button_all = "search_result.filter_hearder.button.all".localized
	static let search_result_filter_hearder_button_none = "search_result.filter_hearder.button.none".localized
	static let search_result_filter_hearder_text = "search_result.filter_hearder.text".localized
	static let search_result_header_text = "search_result.header.text".localized
	static let search_result_sidebar_button_remove = "search_result.sidebar.button.remove".localized
	static let search_result_zimfile_empty_message = "search_result.zimfile.empty.message".localized
	static let search_result_zimfile_no_result_message = "search_result.zimfile.no_result.message".localized
	static let service_worker_warning_label_description = "service_worker_warning.label.description".localized
	static let settings_about_appverion_title = "settings.about.appverion.title".localized
	static let settings_about_build_title = "settings.about.build.title".localized
	static let settings_about_button_license = "settings.about.button.license".localized
	static let settings_about_dependencies = "settings.about.dependencies".localized
	static let settings_about_dependencies_license = "settings.about.dependencies.license".localized
	static let settings_about_dependencies_name = "settings.about.dependencies.name".localized
	static let settings_about_dependencies_version = "settings.about.dependencies.version".localized
	static let settings_about_description = "settings.about.description".localized
	static let settings_about_license_description = "settings.about.license-description".localized
	static let settings_about_our_website_button = "settings.about.our_website.button".localized
	static let settings_about_release = "settings.about.release".localized
	static let settings_about_source_title = "settings.about.source.title".localized
	static let settings_about_title = "settings.about.title".localized
	static let settings_miscellaneous_button_feedback = "settings.miscellaneous.button.feedback".localized
	static let settings_miscellaneous_button_rate_app = "settings.miscellaneous.button.rate_app".localized
	static let settings_miscellaneous_navigation_about = "settings.miscellaneous.navigation.about".localized
	static let settings_miscellaneous_title = "settings.miscellaneous.title".localized
	static let settings_navigation_title = "settings.navigation.title".localized
	static let settings_selected_language_title = "settings.selected_language.title".localized
	static let sidebar_view_navigation_button_close = "sidebar_view.navigation.button.close".localized
	static let sidebar_view_navigation_button_close_all = "sidebar_view.navigation.button.close_all".localized
	static let theme_settings_option_dark = "theme_settings.option.dark".localized
	static let theme_settings_option_light = "theme_settings.option.light".localized
	static let theme_settings_option_system = "theme_settings.option.system".localized
	static let theme_settings_title = "theme_settings.title".localized
	static let welcome_actions_open_file = "welcome.actions.open_file".localized
	static let welcome_button_status_fetch_catalog_text = "welcome.button.status.fetch_catalog.text".localized
	static let welcome_button_status_fetching_catalog_text = "welcome.button.status.fetching_catalog.text".localized
	static let welcome_grid_bookmarks_title = "welcome.grid.bookmarks.title".localized
	static let welcome_loading_data_text = "welcome.loading.data.text".localized
	static let welcome_main_page_title = "welcome.main_page.title".localized
	static let zim_file_action_delete_button_title = "zim_file.action.delete.button.title".localized
	static let zim_file_action_delete_message = "zim_file.action.delete.message".localized
	static let zim_file_action_delete_title = "zim_file.action.delete.title".localized
	static let zim_file_action_download_button_anyway = "zim_file.action.download.button.anyway".localized
	static let zim_file_action_download_title = "zim_file.action.download.title".localized
	static let zim_file_action_download_warning_message = "zim_file.action.download.warning.message".localized
	static let zim_file_action_download_warning_message1 = "zim_file.action.download.warning.message1".localized
	static let zim_file_action_download_warning_title = "zim_file.action.download.warning.title".localized
	static let zim_file_action_locate_title = "zim_file.action.locate.title".localized
	static let zim_file_action_open_main_page_title = "zim_file.action.open_main_page.title".localized
	static let zim_file_action_reveal_in_finder_title = "zim_file.action.reveal_in_finder.title".localized
	static let zim_file_action_toggle_cellular = "zim_file.action.toggle_cellular".localized
	static let zim_file_action_unlink_button_title = "zim_file.action.unlink.button.title".localized
	static let zim_file_action_unlink_message = "zim_file.action.unlink.message".localized
	static func zim_file_action_unlink_multi_message(withArgs args: CVarArg...) -> String { "zim_file.action.unlink.multi_message".localizedWithFormat(withArgs: args) }
	static func zim_file_action_unlink_multi_title(withArgs args: CVarArg...) -> String { "zim_file.action.unlink.multi_title".localizedWithFormat(withArgs: args) }
	static let zim_file_action_unlink_title = "zim_file.action.unlink.title".localized
	static let zim_file_base_info_attribute_category = "zim_file.base_info.attribute.category".localized
	static let zim_file_base_info_attribute_created = "zim_file.base_info.attribute.created".localized
	static let zim_file_base_info_attribute_language = "zim_file.base_info.attribute.language".localized
	static let zim_file_base_info_attribute_size = "zim_file.base_info.attribute.size".localized
	static let zim_file_bool_info_details = "zim_file.bool_info.details".localized
	static let zim_file_bool_info_pictures = "zim_file.bool_info.pictures".localized
	static let zim_file_bool_info_require_service_workers = "zim_file.bool_info.require_service_workers".localized
	static let zim_file_bool_info_videos = "zim_file.bool_info.videos".localized
	static let zim_file_counts_article_media_count = "zim_file.counts.article.media_count".localized
	static let zim_file_counts_article_count = "zim_file.counts.article_count".localized
	static let zim_file_detail_id_title = "zim_file.detail.id.title".localized
	static let zim_file_download_task_action_downloading = "zim_file.download_task.action.downloading".localized
	static let zim_file_download_task_action_failed = "zim_file.download_task.action.failed".localized
	static let zim_file_download_task_action_pause = "zim_file.download_task.action.pause".localized
	static let zim_file_download_task_action_paused = "zim_file.download_task.action.paused".localized
	static let zim_file_download_task_action_resume = "zim_file.download_task.action.resume".localized
	static let zim_file_download_task_action_title_cancel = "zim_file.download_task.action.title.cancel".localized
	static let zim_file_download_task_action_try_recover = "zim_file.download_task.action.try_recover".localized
	static let zim_file_list_actions_text = "zim_file.list.actions.text".localized
	static let zim_file_list_description_text = "zim_file.list.description.text".localized
	static let zim_file_list_info_text = "zim_file.list.info.text".localized
	static let zim_file_list_name_text = "zim_file.list.name.text".localized
	static let zim_file_catalog_fetching_message = "zim_file_catalog.fetching.message".localized
	static let zim_file_category_section_empty_message = "zim_file_category.section.empty.message".localized
	static let zim_file_category_title = "zim_file_category.title".localized
	static let zim_file_cell_article_count_suffix = "zim_file_cell.article_count.suffix".localized
	static let zim_file_downloads_overlay_empty_message = "zim_file_downloads.overlay.empty.message".localized
	static let zim_file_downloads_toolbar_show_sidebar_label = "zim_file_downloads.toolbar.show_sidebar.label".localized
	static let zim_file_missing_indicator_help = "zim_file_missing_indicator.help".localized
	static let zim_file_new_button_refresh = "zim_file_new.button.refresh".localized
	static let zim_file_new_overlay_empty = "zim_file_new_overlay.empty".localized
	static let zim_file_opened_overlay_no_opened_message = "zim_file_opened.overlay.no-opened.message".localized
	static let zim_file_opened_toolbar_open_help = "zim_file_opened.toolbar.open.help".localized
	static let zim_file_opened_toolbar_open_title = "zim_file_opened.toolbar.open.title".localized
	static let zim_file_opened_toolbar_show_sidebar_label = "zim_file_opened.toolbar.show_sidebar.label".localized
}
